/**
 * This file was generated by the JPA Modeler
 */
package km.software.agendago.db;

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * @author jkelsy
 */
@Entity(name = "ArchivoHistorial")
@Table(name = "archivo_historial")
public class ArchivoHistorial implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(targetEntity = Historial.class)
    @JoinColumn(name = "HISTORIAL_ID")
    private Historial historial;

    @ManyToOne(targetEntity = Archivo.class)
    @JoinColumn(name = "ARCHIVO_ID")
    private Archivo archivo;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Historial getHistorial() {
        return this.historial;
    }

    public void setHistorial(Historial historial) {
        this.historial = historial;
    }

    public Archivo getArchivo() {
        return this.archivo;
    }

    public void setArchivo(Archivo archivo) {
        this.archivo = archivo;
    }

}
