/**
 * This file was generated by the JPA Modeler
 */
package km.software.agendago.db;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * @author jkelsy
 */
@Entity(name = "Historial")
@Table(name = "historial")
@NamedQuery(name = "Historial.findByTarea", query = "Select e from Historial e where e.tarea.id = :tareaID")
public class Historial implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Basic
    private Date fecha;

    @Basic
    @Lob
    @Column(name = "observacion", length = Integer.MAX_VALUE)
    private String observacion;

    @ManyToOne(targetEntity = Tarea.class)
    @JoinColumn(name = "TAREA_ID")
    private Tarea tarea;

    @ManyToOne(targetEntity = EstadoTarea.class)
    @JoinColumn(name = "ESTADO_ID")
    private EstadoTarea estado;

    @ManyToOne(targetEntity = Usuario.class)
    @JoinColumn(name = "USUARIO_ID")
    private Usuario usuario;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getObservacion() {
        return this.observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public Tarea getTarea() {
        return this.tarea;
    }

    public void setTarea(Tarea tarea) {
        this.tarea = tarea;
    }

    public EstadoTarea getEstado() {
        return this.estado;
    }

    public void setEstado(EstadoTarea estado) {
        this.estado = estado;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

}
