/**
 * This file was generated by the JPA Modeler
 */
package km.software.agendago.db;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * @author jkelsy
 */
@Entity(name = "Usuario")
@Table(name = "sec_usuario")
@NamedQueries({
    @NamedQuery(name = "Usuario.findByLogin", query = "Select u from Usuario u where u.login=:login")
    ,@NamedQuery(name = "Usuario.findByID", query = "Select e from Usuario e where e.id = :ID")})
@XmlRootElement
public class Usuario implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "usr_password")
    @Basic
    private String password;

    @Column(name = "usr_login")
    @Basic
    private String login;

    @Basic
    private boolean activo;

    @ManyToOne(targetEntity = Persona.class)
    @JoinColumn(name = "PERSONA_ID")
    private Persona persona;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public boolean isActivo() {
        return this.activo;
    }

    public void setActivo(boolean activo) {
        this.activo = activo;
    }

    public Persona getPersona() {
        return this.persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }

}
